from shared.gitmojis import GitmojiEnum

mojis = [
    {
        "type": "fix",
        "icon": GitmojiEnum.FIX.value,
        "code": ":bug:",
        "desc": "Fix a bug.",
    },
    {
        "type": "feat",
        "icon": GitmojiEnum.FEAT.value,
        "code": ":sparkles:",
        "desc": "Introduce new features.",
    },
    {
        "type": "docs",
        "icon": GitmojiEnum.DOCS.value,
        "code": ":memo:",
        "desc": "Add or update documentation.",
    },
    {
        "type": "style",
        "icon": GitmojiEnum.STYLE.value,
        "code": ":art:",
        "desc": "Improve structure / format of the code.",
    },
    {
        "type": "refactor",
        "icon": GitmojiEnum.REFACTOR.value,
        "code": ":recycle:",
        "desc": "Refactor code.",
    },
    {
        "type": "test",
        "icon": GitmojiEnum.TEST_FAIL.value,
        "code": ":test_tube:",
        "desc": "Add, update, or pass tests.",
    },
    {
        "type": "build",
        "icon": GitmojiEnum.BUILD.value,
        "code": ":construction_worker:",
        "desc": "Add or update CI build system.",
    },
    {
        "type": "ci",
        "icon": GitmojiEnum.CI.value,
        "code": ":green_heart:",
        "desc": "Fix CI Build.",
    },
    {
        "type": "revert",
        "icon": GitmojiEnum.REVERT.value,
        "code": ":rewind:",
        "desc": "Revert changes.",
    },
    {
        "type": "dump",
        "icon": GitmojiEnum.DUMP.value,
        "code": ":fire:",
        "desc": "Remove code or files.",
    },
    {
        "type": "hotfix",
        "icon": GitmojiEnum.HOTFIX.value,
        "code": ":ambulance:",
        "desc": "Critical hotfix.",
    },
    {
        "type": "deploy",
        "icon": GitmojiEnum.DEPLOY.value,
        "code": ":rocket:",
        "desc": "Deploy stuff.",
    },
    {
        "type": "ui",
        "icon": GitmojiEnum.UI.value,
        "code": ":lipstick:",
        "desc": "Add or update the UI and style files.",
    },
    {
        "type": "init",
        "icon": GitmojiEnum.INIT.value,
        "code": ":tada:",
        "desc": "Begin a project.",
    },
    {
        "type": "secret",
        "icon": GitmojiEnum.SECRET.value,
        "code": ":closed_lock_with_key:",
        "desc": "Add or update secrets.",
    },
    {
        "type": "bump",
        "icon": GitmojiEnum.BUMP.value,
        "code": ":bookmark:",
        "desc": "Release / Version tags.",
    },
    {
        "type": "fix-lint",
        "icon": GitmojiEnum.FIX_LINT.value,
        "code": ":rotating_light:",
        "desc": "Fix compiler / linter warnings.",
    },
    {
        "type": "wip",
        "icon": GitmojiEnum.WIP.value,
        "code": ":construction:",
        "desc": "Work in progress.",
    },
    {
        "type": "dep-drop",
        "icon": GitmojiEnum.DEP_DROP.value,
        "code": ":arrow_down:",
        "desc": "Downgrade dependencies.",
    },
    {
        "type": "dep-bump",
        "icon": GitmojiEnum.DEP_BUMP.value,
        "code": ":arrow_up:",
        "desc": "Upgrade dependencies.",
    },
    {
        "type": "pin",
        "icon": GitmojiEnum.PIN.value,
        "code": ":pushpin:",
        "desc": "Pin dependencies to specific versions.",
    },
    {
        "type": "dep-add",
        "icon": GitmojiEnum.DEP_ADD.value,
        "code": ":heavy_plus_sign:",
        "desc": "Add a dependency.",
    },
    {
        "type": "dep-rm",
        "icon": GitmojiEnum.DEP_RM.value,
        "code": ":heavy_minus_sign:",
        "desc": "Remove a dependency.",
    },
    {
        "type": "config",
        "icon": GitmojiEnum.CONFIG.value,
        "code": ":wrench:",
        "desc": "Add or update configuration files.",
    },
    {
        "type": "script",
        "icon": GitmojiEnum.SCRIPT.value,
        "code": ":hammer:",
        "desc": "Add or update development scripts.",
    },
    {
        "type": "typo",
        "icon": GitmojiEnum.TYPO.value,
        "code": ":pencil2:",
        "desc": "Fix typos.",
    },
    {
        "type": "merge",
        "icon": GitmojiEnum.MERGE.value,
        "code": ":twisted_rightwards_arrows:",
        "desc": "Merge branches.",
    },
    {
        "type": "package",
        "icon": GitmojiEnum.PACKAGE.value,
        "code": ":package:",
        "desc": "Add or update compiled files or packages.",
    },
    {
        "type": "resource",
        "icon": GitmojiEnum.RESOURCE.value,
        "code": ":truck:",
        "desc": "Move or rename resources (e.g.: files, paths, routes).",
    },
    {
        "type": "license",
        "icon": GitmojiEnum.LICENSE.value,
        "code": ":page_facing_up:",
        "desc": "Add or update license.",
    },
    {
        "type": "asset",
        "icon": GitmojiEnum.ASSET.value,
        "code": ":bento:",
        "desc": "Add or update assets.",
    },
    {
        "type": "db",
        "icon": GitmojiEnum.DB.value,
        "code": ":card_file_box:",
        "desc": "Perform database related changes.",
    },
    {
        "type": "arch",
        "icon": GitmojiEnum.ARCH.value,
        "code": ":building_construction:",
        "desc": "Make architectural changes.",
    },
    {
        "type": "design",
        "icon": GitmojiEnum.DESIGN.value,
        "code": ":iphone:",
        "desc": "Work on responsive design.",
    },
    {
        "type": "ignore",
        "icon": GitmojiEnum.IGNORE.value,
        "code": ":see_no_evil:",
        "desc": "Add or update a .gitignore file.",
    },
    {
        "type": "snap",
        "icon": GitmojiEnum.SNAP.value,
        "code": ":camera_flash:",
        "desc": "Add or update snapshots.",
    },
    {
        "type": "deprecation",
        "icon": GitmojiEnum.DEPRECATION.value,
        "code": ":wastebasket:",
        "desc": "Deprecate code that needs to be cleaned up.",
    },
    {
        "type": "devxp",
        "icon": GitmojiEnum.DEVXP.value,
        "code": ":technologist:",
        "desc": "Improve developer experience.",
    },
    {
        "type": "chore",
        "icon": GitmojiEnum.CHORE.value,
        "code": ":broom:",
        "desc": "Commit changes related to miscelaneous chores.",
    },
    {
        "type": "squash",
        "icon": GitmojiEnum.SQUASH.value,
        "code": ":point_down:",
        "desc": "Squash commits.",
    },
    {
        "type": "fixup",
        "icon": GitmojiEnum.FIXUP.value,
        "code": ":dotted_line_face:",
        "desc": "Fixup commits.",
    },
]
